### ISSUE TITLE
"Compression" Parameter Missing

### ISSUE THREAD

**Issue by oikand** [hazzik/nhibernate-lob#1]
I used the updated project with NHibernate 5.2.3 but I'm getting a run-time error on "GetBlobSettings" method of file "Parameters.cs". After some debugging, the error is related with the missing key "compression" in the parameters dictionary variable.
On my project I don't use any type of compression, so this parameter should exist as null. The same code but with NHibernate 4.1.2 works smoothly without any issues.
In order to fix it, I applied the following code changes:

```csharp
string compr = null;
if (parameters != null) parameters.TryGetValue("compression", out compr);
//string compr = parameters == null ? null : parameters["compression"];
```

Attached is the whole file. In general, how can I set a value to this parameter?

Regards,
Andreas
[Parameters.zip](https://github.com/hazzik/nhibernate-lob/files/2879238/Parameters.zip)

**Comment by hazzik** [comment]
Thanks. Fixed.
